language: erlang
otp_release:
   - 17.0

before_install:
  - "export DISPLAY=:99.0"
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"
  - mkdir $HOME/src
  - npm install -g phantomjs
  - bash $TRAVIS_BUILD_DIR/test/tools/start_webdriver.sh
  - git clone https://github.com/elixir-lang/elixir.git $HOME/src/elixir
  - export PATH=$PATH:$HOME/src/elixir/bin/
  - cd $HOME/src/elixir && git checkout $ELIXIR_VERSION && make clean compile && cd -
  - mix local.hex --force

env:
  - WEBDRIVER=selenium   ELIXIR_VERSION="v0.14.2"
  - WEBDRIVER=phantomjs  ELIXIR_VERSION="v0.14.2"

install: mix deps.get
script:  mix test
