language: erlang
otp_release:
   - R16B

before_install:
  - "export DISPLAY=:99.0"
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"
  - mkdir $HOME/src
  - bash $TRAVIS_BUILD_DIR/test/tools/start_webdriver.sh
  - git clone https://github.com/elixir-lang/elixir.git $HOME/src/elixir
  - export PATH=$PATH:$HOME/src/elixir/bin/
  - export ELIXIR_VERSION=v0.12.0
  - cd $HOME/src/elixir && git checkout $ELIXIR_VERSION && make clean compile && cd -
env:
  - WEBDRIVER=selenium
  - WEBDRIVER=phantomjs

install: mix deps.get
script:  mix test
